DELETE FROM [UTILISATEURS]
ALTER TABLE [UTILISATEURS] DROP COLUMN email
ALTER TABLE [UTILISATEURS] ADD email varchar(100)

SELECT * FROM [ARTICLES_VENDUS]
ALTER TABLE [ARTICLES_VENDUS] DROP COLUMN [description]
ALTER TABLE [ARTICLES_VENDUS] ADD [description] varchar(1000)